services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
