services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./uploads:/app/uploads  # Shared volume for file storage
    networks:
      - app-network

  worker:
    build: .
    container_name: worker
    depends_on:
      - redis
      - nextjs-app
      - external-api
    environment:
      REDIS_HOST: redis
    command: ["node", "jobs/worker.js"]
    volumes:
      - ./uploads:/app/uploads  # Shared volume for file access
    networks:
      - app-network

  external-api:
    build: ./api  # Path to external API service
    container_name: external-api
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
